name: Deploy Docker Image

on:
  push:
    branches:
      - main
    jobs:
      Deploy:
        runs-on: windows-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v2
          - name: Login to GitHub Container Registry
            uses: docker/login-action@v1
            with:
              registry: ghcr.io
              username: ${{ github.repository_owner }}
              password: ${{ secrets.GITHUB_TOKEN }}
          -name: Build and push Docker image
            uses: docker/build-push-action@v2
            with:
              context: .
              file: ./Dockerfile
              push: true
              tags: ghcr.io/${{ github.repository_owner }}/react-node:latest
      
